spring.application.name=authentication-service
server.port=8082


# Keycloak configuration
keycloak.server.url=http://localhost:8081
keycloak.realm=voting-system-realm
keycloak.client.id=spring-authentication-service
keycloak.client.secret=SSqCI12df5HJDnzN25zswM6j7ghsEo9x